---
title: "Dados"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment=NULL)
```

# Abaixo os dados da componente neonatal
```{r}
neo<-structure(list(Y = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), 
    ESCMAE = c(5L, 3L, 5L, 3L, 4L, 5L, 4L, 5L, 5L, 5L, 4L, 5L, 
    4L, 5L, 5L, 2L, 3L, 5L, 5L, 4L, 4L, 3L, 4L, 1L, 5L, 4L, 5L, 
    4L, 4L, 5L, 4L, 5L, 4L, 5L, 5L, 4L, 5L, 4L, 4L, 5L, 5L, 5L, 
    3L, 5L, 5L, 3L, 4L, 5L, 5L, 5L, 3L, 5L, 3L, 4L, 5L, 5L, 4L, 
    5L, 3L, 2L, 5L, 3L, 4L, 4L, 4L, 3L, 5L, 3L, 3L, 4L, 5L, 4L, 
    4L, 5L, 5L, 4L, 5L, 5L, 3L, 3L, 4L, 4L, 3L, 5L, 4L, 5L, 5L, 
    3L, 5L, 4L, 4L, 5L, 5L, 3L, 4L, 5L, 5L, 3L, 5L, 5L, 5L, 4L, 
    4L, 3L, 3L, 4L, 4L, 3L, 2L, 4L, 2L, 5L, 5L, 5L, 5L, 5L, 5L, 
    3L, 5L, 4L, 2L, 4L, 5L, 4L, 5L, 4L, 5L, 5L, 3L, 5L, 5L, 5L, 
    5L, 3L, 3L, 5L, 5L, 5L, 2L, 4L, 5L, 4L, 4L, 2L, 3L, 2L, 3L, 
    4L, 5L, 4L, 3L, 5L, 3L, 5L, 4L, 4L, 4L, 2L, 5L, 5L, 5L, 5L, 
    3L, 5L, 4L, 3L, 5L, 5L, 4L, 5L, 5L, 5L, 5L, 5L, 3L, 5L, 3L, 
    4L, 3L, 3L, 4L, 4L, 5L, 5L, 5L, 4L, 5L, 4L, 5L, 3L, 4L, 5L, 
    5L, 4L, 4L, 4L, 4L, 3L, 4L, 5L, 3L, 4L, 3L, 3L, 5L, 4L, 4L, 
    5L, 5L, 4L, 3L, 3L, 4L, 5L, 5L, 2L, 5L, 4L, 4L, 5L, 3L, 4L, 
    5L, 3L, 5L, 4L, 3L, 5L, 4L, 3L, 4L, 5L, 3L, 4L, 5L, 3L, 3L, 
    3L, 5L, 3L, 3L, 4L, 5L, 5L, 5L, 5L, 4L, 5L, 4L, 4L, 5L, 5L, 
    4L, 2L, 4L, 3L, 4L, 3L, 3L, 5L, 5L, 5L, 5L, 4L, 4L, 4L, 4L, 
    4L, 5L, 5L, 3L, 5L, 5L, 4L, 2L, 4L, 3L, 3L, 1L, 3L, 5L, 3L, 
    4L, 4L, 4L, 5L, 3L, 3L, 4L, 4L, 4L, 4L, 4L, 5L, 1L, 5L, 4L, 
    5L, 5L, 4L, 4L, 4L, 3L, 3L, 4L, 3L, 4L, 4L, 4L, 4L, 5L, 4L, 
    3L, 4L, 4L, 3L, 4L, 3L, 4L, 4L, 4L, 5L, 3L, 5L, 5L, 5L, 2L, 
    4L, 4L, 3L, 4L, 4L, 3L, 4L, 4L, 5L, 5L, 5L, 9L, 3L, 4L, 5L, 
    4L, 4L, 5L, 3L, 3L, 3L, 4L, 5L, 4L, 3L, 3L, 3L, 5L, 5L, 4L, 
    4L, 4L, 5L, 3L, 4L, 4L, 3L, 3L, 5L, 5L, 4L, 5L, 4L, 4L, 4L, 
    4L, 4L, 5L, 4L, 4L, 4L, 4L, 5L, 3L, 5L, 4L, 3L, 4L, 5L, 4L, 
    4L, 3L, 3L, 4L, 3L, 3L, 4L, 4L, 5L, 4L, 4L, 4L, 3L, 3L, 4L, 
    5L, 4L, 1L, 2L, 2L, 5L, 3L), ESTCIVMAE = c(1L, 1L, 2L, 2L, 
    2L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 
    2L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 
    2L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 
    1L, 2L, 1L, 1L, 2L, 2L, 2L, 1L, 2L, 4L, 1L, 2L, 2L, 2L, 1L, 
    2L, 1L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 
    1L, 2L, 2L, 1L, 2L, 2L, 2L, 4L, 2L, 2L, 1L, 1L, 2L, 1L, 2L, 
    2L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 4L, 
    1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 4L, 2L, 2L, 2L, 2L, 
    2L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 
    2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 2L, 1L, 1L, 2L, 2L, 1L, 
    2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 2L, 
    2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 
    2L, 1L, 2L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
    1L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 
    2L, 1L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 
    2L, 2L, 2L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 
    1L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 2L, 
    2L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 1L, 2L, 
    1L, 4L, 1L, 2L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 2L, 
    1L, 1L, 1L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 
    1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 
    2L, 1L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 1L, 1L, 2L, 1L, 1L, 2L, 
    2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 
    2L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 
    1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 4L, 
    2L, 1L, 1L, 1L, 3L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 2L, 
    1L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 1L, 1L, 2L
    ), GESTACAO = c(5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 4L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 4L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 3L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    4L, 5L, 5L, 5L, 5L, 5L, 5L, 4L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    4L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 4L, 5L, 5L, 5L, 4L, 5L, 5L, 5L, 5L, 6L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 4L, 5L, 4L, 5L, 4L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 3L, 5L, 5L, 4L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 4L, 5L, 4L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 4L, 5L, 4L, 5L, 5L, 5L, 5L, 
    5L, 5L, 4L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 2L, 5L, 3L, 2L, 5L, 4L, 5L, 2L, 
    5L, 3L, 2L, 5L, 1L, 2L, 3L, 2L, 1L, 2L, 5L, 2L, 2L, 3L, 2L, 
    5L, 5L, 1L, 2L, 2L, 4L, 2L, 2L, 5L, 5L, 5L, 5L, 5L, 4L, 5L, 
    5L, 4L, 5L, 2L, 4L, 3L, 5L, 4L, 2L, 4L, 3L, 2L, 5L, 3L, 3L, 
    2L, 4L, 3L, 2L, 2L, 3L, 3L, 2L, 4L, 5L, 2L, 5L, 4L, 2L, 4L, 
    2L, 4L, 4L, 5L, 4L, 2L, 4L, 2L, 4L, 5L, 5L, 5L, 2L, 2L, 2L, 
    5L, 4L, 5L, 5L, 3L, 5L, 5L, 5L, 2L, 2L, 4L, 2L, 4L, 3L, 2L, 
    5L, 3L, 3L, 2L, 2L, 5L, 2L, 4L, 2L, 5L, 2L, 5L, 5L, 5L, 4L, 
    2L, 4L, 4L, 4L, 3L, 5L, 2L, 4L, 4L, 3L, 5L, 3L, 5L, 5L, 4L, 
    2L, 5L, 2L, 5L, 4L, 5L, 5L, 5L), GRAVIDEZ = c(1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 3L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 
    1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L), IDADEMAE = c(22L, 20L, 39L, 19L, 34L, 24L, 29L, 22L, 
    29L, 34L, 40L, 20L, 36L, 24L, 29L, 24L, 29L, 31L, 31L, 26L, 
    19L, 25L, 42L, 29L, 21L, 19L, 24L, 21L, 34L, 18L, 30L, 28L, 
    33L, 27L, 32L, 25L, 31L, 37L, 29L, 21L, 27L, 29L, 21L, 22L, 
    20L, 25L, 43L, 29L, 36L, 33L, 25L, 27L, 28L, 30L, 22L, 28L, 
    22L, 33L, 38L, 32L, 33L, 14L, 27L, 24L, 25L, 24L, 31L, 18L, 
    16L, 31L, 32L, 26L, 24L, 33L, 30L, 17L, 17L, 20L, 38L, 25L, 
    25L, 26L, 21L, 29L, 35L, 39L, 34L, 38L, 28L, 17L, 26L, 27L, 
    25L, 25L, 32L, 25L, 25L, 20L, 34L, 27L, 37L, 20L, 19L, 13L, 
    19L, 20L, 24L, 20L, 30L, 25L, 37L, 29L, 25L, 34L, 35L, 28L, 
    30L, 26L, 29L, 27L, 22L, 25L, 32L, 17L, 30L, 27L, 35L, 35L, 
    33L, 28L, 26L, 28L, 33L, 25L, 26L, 29L, 31L, 29L, 35L, 15L, 
    21L, 37L, 25L, 22L, 21L, 33L, 34L, 19L, 26L, 21L, 20L, 29L, 
    16L, 19L, 31L, 35L, 27L, 33L, 31L, 23L, 25L, 27L, 34L, 25L, 
    22L, 36L, 26L, 34L, 26L, 20L, 26L, 34L, 30L, 21L, 22L, 30L, 
    31L, 29L, 27L, 24L, 20L, 31L, 23L, 32L, 41L, 30L, 29L, 21L, 
    29L, 29L, 18L, 24L, 31L, 31L, 37L, 22L, 34L, 43L, 15L, 21L, 
    29L, 16L, 27L, 24L, 21L, 26L, 26L, 32L, 28L, 30L, 24L, 25L, 
    33L, 27L, 27L, 33L, 30L, 19L, 25L, 29L, 44L, 20L, 31L, 22L, 
    30L, 28L, 22L, 29L, 37L, 19L, 29L, 23L, 17L, 30L, 23L, 28L, 
    27L, 16L, 29L, 21L, 33L, 17L, 32L, 24L, 28L, 30L, 22L, 19L, 
    24L, 31L, 31L, 34L, 17L, 20L, 34L, 18L, 24L, 17L, 21L, 35L, 
    22L, 36L, 29L, 22L, 19L, 29L, 22L, 33L, 35L, 18L, 27L, 29L, 
    29L, 26L, 18L, 34L, 15L, 23L, 36L, 23L, 23L, 20L, 29L, 30L, 
    29L, 26L, 34L, 16L, 18L, 24L, 16L, 22L, 22L, 35L, 18L, 19L, 
    32L, 34L, 19L, 28L, 20L, 32L, 19L, 29L, 24L, 16L, 23L, 27L, 
    19L, 31L, 17L, 28L, 27L, 19L, 40L, 34L, 34L, 21L, 36L, 25L, 
    23L, 28L, 19L, 30L, 20L, 41L, 19L, 38L, 17L, 18L, 22L, 17L, 
    26L, 32L, 21L, 32L, 23L, 26L, 32L, 15L, 23L, 28L, 30L, 33L, 
    32L, 19L, 29L, 28L, 21L, 40L, 17L, 23L, 21L, 33L, 23L, 37L, 
    26L, 25L, 22L, 26L, 35L, 24L, 22L, 26L, 38L, 31L, 20L, 29L, 
    24L, 31L, 19L, 30L, 31L, 24L, 26L, 24L, 20L, 16L, 40L, 32L, 
    15L, 30L, 26L, 18L, 24L, 26L, 17L, 26L, 29L, 28L, 17L, 27L, 
    25L, 23L, 23L, 30L, 30L, 17L, 29L, 41L, 19L, 23L, 30L, 19L, 
    28L, 29L, 25L, 27L, 32L), PARTO = c(1L, 1L, 2L, 1L, 1L, 2L, 
    2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 1L, 1L, 2L, 2L, 1L, 1L, 
    2L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 
    2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 2L, 1L, 
    2L, 2L, 2L, 1L, 2L, 1L, 1L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 1L, 
    2L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 1L, 1L, 
    1L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 
    2L, 1L, 2L, 1L, 2L, 1L, 1L, 1L, 1L, 2L, 2L, 1L, 2L, 1L, 1L, 
    2L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 1L, 1L, 2L, 1L, 1L, 2L, 
    2L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 
    1L, 2L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 2L, 2L, 1L, 2L, 2L, 
    2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 
    2L, 2L, 1L, 1L, 2L, 2L, 1L, 1L, 1L, 1L, 2L, 1L, 2L, 2L, 2L, 
    2L, 2L, 2L, 2L, 1L, 1L, 2L, 2L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 
    1L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 
    2L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 1L, 1L, 
    2L, 1L, 1L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 
    2L, 1L, 1L, 1L, 2L, 2L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 2L, 
    2L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 
    2L, 2L, 1L, 2L, 1L, 1L, 2L, 2L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 
    2L, 1L, 1L, 1L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 1L, 2L, 1L, 
    2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 
    2L, 2L, 2L, 2L, 1L, 1L, 2L, 2L, 1L, 1L, 2L, 2L, 1L, 2L, 2L, 
    2L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 
    2L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 1L, 1L, 
    1L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 1L, 1L, 
    2L, 1L, 1L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 
    2L, 2L, 2L, 2L, 1L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 2L), PESO = c(2880L, 
    3340L, 3445L, 2970L, 2395L, 3600L, 2995L, 2930L, 3220L, 2680L, 
    3535L, 3170L, 3400L, 3030L, 3000L, 3310L, 2210L, 3715L, 3700L, 
    3750L, 3310L, 4130L, 3070L, 2750L, 3265L, 3285L, 3410L, 3350L, 
    1900L, 3600L, 3035L, 2400L, 2775L, 2745L, 2740L, 3050L, 3510L, 
    2975L, 3245L, 3840L, 3505L, 3625L, 3420L, 3280L, 2770L, 2700L, 
    2580L, 3335L, 3610L, 3125L, 2880L, 3130L, 3680L, 3240L, 3650L, 
    3205L, 2325L, 3530L, 3380L, 3230L, 2795L, 2740L, 3050L, 2620L, 
    2920L, 3865L, 3275L, 2505L, 3355L, 3320L, 3130L, 3500L, 3255L, 
    3585L, 3800L, 3100L, 2725L, 3710L, 3480L, 4025L, 2790L, 2980L, 
    3035L, 4160L, 3010L, 3060L, 2980L, 3525L, 2945L, 2950L, 3100L, 
    3050L, 3370L, 3315L, 3080L, 3965L, 3050L, 4325L, 3350L, 3450L, 
    3150L, 3000L, 3240L, 2740L, 2970L, 2785L, 3380L, 2945L, 3800L, 
    2360L, 3410L, 2770L, 3210L, 2860L, 2115L, 1410L, 3830L, 3560L, 
    3900L, 1950L, 3270L, 3180L, 3900L, 2580L, 3345L, 3465L, 3320L, 
    3750L, 3780L, 2950L, 3120L, 2055L, 3100L, 2680L, 3310L, 2750L, 
    3105L, 3210L, 2410L, 3280L, 3100L, 2840L, 4230L, 2930L, 3455L, 
    2800L, 2825L, 3125L, 2850L, 3890L, 2440L, 3220L, 3360L, 3330L, 
    3005L, 2960L, 3365L, 3785L, 2730L, 2515L, 2720L, 3155L, 3000L, 
    2395L, 3600L, 3230L, 2890L, 2850L, 2970L, 2380L, 3450L, 3685L, 
    3435L, 2955L, 3070L, 3130L, 2845L, 2890L, 2700L, 3780L, 4180L, 
    3310L, 1525L, 3620L, 2700L, 3430L, 2130L, 3390L, 3385L, 3110L, 
    2870L, 2815L, 3670L, 2910L, 3895L, 3350L, 3500L, 1500L, 3550L, 
    2630L, 1450L, 3350L, 3450L, 3055L, 3590L, 3630L, 3085L, 3295L, 
    3200L, 3340L, 1825L, 3300L, 2110L, 3840L, 3190L, 2900L, 3860L, 
    2635L, 3310L, 3390L, 2580L, 3745L, 3300L, 3130L, 3260L, 2000L, 
    3840L, 2800L, 3135L, 2340L, 3310L, 2350L, 2910L, 3600L, 2620L, 
    3250L, 2040L, 2885L, 3085L, 3460L, 3030L, 3385L, 3340L, 3870L, 
    3750L, 2830L, 3340L, 2410L, 3160L, 3315L, 3600L, 4155L, 3335L, 
    3430L, 3780L, 3390L, 2650L, 3000L, 3495L, 2800L, 2890L, 4275L, 
    3570L, 2120L, 3080L, 2875L, 2950L, 3075L, 3310L, 3575L, 3215L, 
    3230L, 3610L, 510L, 3550L, 1285L, 1165L, 2460L, 2235L, 4220L, 
    580L, 1680L, 450L, 1110L, 3285L, 410L, 410L, 580L, 820L, 
    535L, 480L, 2205L, 610L, 700L, 1200L, 690L, 2760L, 3445L, 
    380L, 565L, 380L, 1700L, 880L, 715L, 2640L, 2620L, 4020L, 
    3500L, 3560L, 1230L, 2690L, 2160L, 1510L, 2650L, 800L, 3445L, 
    1520L, 2510L, 1860L, 480L, 1840L, 1330L, 1015L, 3890L, 1650L, 
    1280L, 1045L, 2675L, 1330L, 710L, 745L, 1370L, 1115L, 810L, 
    2580L, 3395L, 400L, 2940L, 2030L, 900L, 2250L, 830L, 890L, 
    2850L, 3730L, 2335L, 865L, 2490L, 430L, 2350L, 1830L, 2885L, 
    3890L, 430L, 690L, 730L, 2030L, 1465L, 2890L, 3095L, 1350L, 
    3005L, 1940L, 3115L, 760L, 750L, 1505L, 610L, 1380L, 935L, 
    1350L, 3080L, 945L, 920L, 770L, 785L, 3000L, 660L, 1400L, 
    940L, 3350L, 800L, 3665L, 2870L, 2230L, 2820L, 660L, 950L, 
    1455L, 2175L, 1060L, 3050L, 945L, 2630L, 1625L, 1320L, 3730L, 
    1310L, 3400L, 2880L, 1930L, 695L, 2605L, 850L, 2840L, 1635L, 
    2035L, 2900L, 2815L), QTDFILMORT = c(0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 
    0L, 1L, 0L, 0L, 0L, 2L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 4L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 
    0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 1L, 0L, 0L, 
    0L, 0L, 0L, 1L, 0L, 0L, 0L, 2L, 0L, 0L, 0L, 0L, 0L, 2L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 
    0L, 2L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L), 
    QTDFILVIVO = c(1L, 2L, 0L, 0L, 1L, 0L, 1L, 0L, 1L, 1L, 1L, 
    0L, 1L, 0L, 2L, 3L, 1L, 0L, 0L, 3L, 0L, 0L, 0L, 0L, 1L, 0L, 
    1L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 2L, 1L, 0L, 
    1L, 2L, 1L, 0L, 1L, 2L, 0L, 3L, 0L, 1L, 0L, 0L, 0L, 1L, 1L, 
    0L, 1L, 3L, 3L, 0L, 0L, 1L, 2L, 0L, 2L, 0L, 0L, 1L, 0L, 1L, 
    0L, 0L, 1L, 1L, 0L, 0L, 0L, 2L, 1L, 0L, 0L, 1L, 0L, 2L, 1L, 
    1L, 1L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 1L, 1L, 
    0L, 0L, 0L, 1L, 0L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 2L, 0L, 
    1L, 2L, 1L, 2L, 2L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 
    1L, 0L, 2L, 2L, 1L, 0L, 2L, 6L, 0L, 1L, 2L, 0L, 2L, 3L, 3L, 
    2L, 0L, 3L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 8L, 2L, 0L, 1L, 
    1L, 0L, 0L, 0L, 3L, 0L, 2L, 1L, 0L, 0L, 0L, 1L, 0L, 1L, 1L, 
    0L, 1L, 3L, 2L, 1L, 1L, 1L, 0L, 0L, 1L, 0L, 1L, 0L, 3L, 0L, 
    3L, 1L, 0L, 2L, 0L, 1L, 2L, 0L, 0L, 0L, 0L, 1L, 3L, 0L, 3L, 
    0L, 0L, 0L, 2L, 0L, 1L, 1L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 2L, 
    0L, 2L, 0L, 0L, 0L, 0L, 0L, 2L, 0L, 1L, 2L, 1L, 1L, 1L, 1L, 
    1L, 0L, 0L, 0L, 2L, 0L, 0L, 3L, 1L, 0L, 0L, 0L, 1L, 2L, 1L, 
    0L, 0L, 1L, 0L, 0L, 1L, 0L, 0L, 2L, 0L, 1L, 0L, 0L, 0L, 0L, 
    1L, 1L, 3L, 0L, 2L, 0L, 1L, 0L, 0L, 3L, 1L, 0L, 6L, 1L, 0L, 
    3L, 1L, 0L, 0L, 0L, 5L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    2L, 1L, 0L, 1L, 0L, 0L, 0L, 4L, 0L, 0L, 0L, 4L, 0L, 2L, 0L, 
    3L, 1L, 1L, 2L, 3L, 0L, 1L, 2L, 0L, 0L, 1L, 1L, 1L, 0L, 0L, 
    1L, 3L, 0L, 0L, 1L, 0L, 3L, 1L, 0L, 1L, 0L, 0L, 2L, 0L, 0L, 
    0L, 0L, 2L, 1L, 2L, 1L, 3L, 0L, 1L, 0L, 0L, 2L, 2L, 0L, 1L, 
    1L, 0L, 1L, 0L, 3L, 1L, 0L, 4L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 
    1L, 0L, 0L, 1L, 1L, 1L, 0L, 2L, 0L, 0L, 0L, 2L, 0L, 0L, 0L, 
    1L, 1L, 1L, 2L, 0L, 3L, 1L, 0L, 1L, 2L, 1L, 0L, 1L, 0L, 1L, 
    1L, 0L, 0L, 3L, 4L, 7L, 0L, 1L), RACACOR = c(1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 4L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 4L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 4L, 
    1L, 4L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L), SEXO = structure(c(1L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 
    1L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 
    1L, 1L, 2L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 
    1L, 2L, 1L, 2L, 1L, 1L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 2L, 
    2L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 2L, 
    1L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 2L, 2L, 
    2L, 1L, 1L, 1L, 1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 2L, 
    1L, 1L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 
    1L, 2L, 1L, 1L, 2L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 
    1L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 
    1L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 1L, 1L, 2L, 2L, 
    1L, 1L, 1L, 2L, 2L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 2L, 2L, 1L, 
    1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 2L, 
    1L, 1L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 1L, 
    1L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 
    2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 1L, 1L, 1L, 2L, 1L, 2L, 
    2L, 1L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 2L, 
    1L, 2L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 1L, 
    1L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 
    1L, 2L, 1L, 1L, 1L, 2L, 1L, 1L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 
    1L, 1L, 1L, 2L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 2L, 
    2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 
    2L, 2L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 1L, 
    1L, 1L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 1L, 1L, 2L, 
    2L, 2L, 1L, 2L, 2L, 1L, 1L, 2L, 2L, 1L, 2L, 2L, 1L, 1L, 2L, 
    2L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 
    2L, 2L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 2L), .Label = c("F", 
    "M"), class = "factor"), XCOORD = c(673900.060449579, 677679.073215458, 
    680023.90279867, 680088.187134967, 666810.264935606, 668745.027027093, 
    673935.451059867, 679525.44069412, 675100.795144732, 666184.42832553, 
    675964.616225224, 666692.791184728, 671883.97719293, 672976.51455735, 
    679543.452979832, 675222.774810515, 671086.862103729, 670959.550411254, 
    676467.881605888, 668669.251746042, 678149.724096206, 673919.990837113, 
    673473.447496859, 673727.754412655, 673903.47960699, 677803.173729077, 
    666619.894022888, 665415.851729729, 672911.788812773, 676058.151989887, 
    666429.570763935, 676200.286180767, 670632.098905807, 668513.996014312, 
    671554.676518771, 675037.398232291, 676890.047553373, 669401.276883253, 
    678753.030199496, 674252.707690826, 673623.565197191, 676426.853362516, 
    672290.883226311, 673866.825087442, 665121.469991704, 672758.902365385, 
    670760.155103139, 671875.607920792, 674390.046431309, 668995.409626741, 
    668685.348296695, 675648.754228735, 669170.266064726, 674180.688894868, 
    674539.110191483, 671805.487030254, 671193.888450145, 675578.80322932, 
    667807.918567127, 672255.699997169, 676225.909617342, 669531.425424442, 
    680243.204668531, 668509.00879703, 668795.428916923, 675180.088829745, 
    675616.404110848, 666667.22251195, 672385.926006664, 668388.529292964, 
    666084.596040729, 676803.977519984, 672789.571956362, 670014.391048442, 
    675801.160709656, 678942.68260576, 667055.990854463, 674665.932251757, 
    677927.459552716, 667874.611368757, 669925.199996859, 680132.585844498, 
    673837.187126339, 672076.123225443, 676361.094404105, 674485.124547573, 
    670324.821637409, 672986.204475819, 678098.07786395, 672462.348796172, 
    666143.678382315, 675424.554470682, 677579.461209829, 679890.127576607, 
    668833.796359006, 679015.49679384, 677264.895306089, 667614.765539057, 
    675797.717728565, 669578.918982908, 675364.028676568, 671942.349806456, 
    667772.129171518, 675420.132002048, 675999.724048889, 671565.260755304, 
    679504.637476837, 676431.42349346, 671565.260755304, 676654.062198735, 
    678714.13568921, 680173.882754849, 676299.949725862, 670354.780320648, 
    672261.240055535, 675555.323808133, 676845.309731572, 680442.130170611, 
    668336.492987006, 670895.800344159, 672699.511568854, 678398.824238539, 
    667370.128009243, 673909.730813833, 671136.112926865, 671979.620071533, 
    678938.33554685, 674541.602733188, 673405.035516019, 674424.252814375, 
    667882.308759857, 674213.493763137, 670781.46726542, 675829.930961278, 
    678871.514009071, 673034.242586752, 680048.978114922, 667626.310764963, 
    673329.285949351, 674764.714673749, 670680.900626284, 670520.297278726, 
    675836.46561799, 680669.694523602, 680423.249878179, 680771.361967681, 
    671294.306605216, 676772.915678561, 673144.380331901, 669851.599760152, 
    672215.710692632, 667770.562810446, 674604.8645085, 672374.185527607, 
    666809.436963343, 673990.42842678, 675194.092326978, 681186.200373306, 
    675180.088829745, 671217.937947077, 665722.351824322, 671861.302499315, 
    670742.764168471, 671615.852014707, 678516.030020895, 680854.770255801, 
    671376.644330009, 673565.160051667, 670081.9, 676400.086229811, 
    675724.968366759, 674687.080514263, 671958.28459057, 676643.208852619, 
    675922.780104158, 672245.371259095, 677575.006468496, 674208.348037926, 
    666384.141153468, 668697.103003955, 675600.59915345, 680999.183228328, 
    676089.625665976, 673121.848649725, 668749.073694574, 668371.55930081, 
    674733.509285784, 679734.794048832, 679746.803503771, 672194.256689062, 
    667281.595242129, 673017.251472337, 680514.743341167, 666188.349144311, 
    677399.903090554, 668674.032334575, 677584.532498933, 670715.4, 
    673069.140782636, 667264.91352088, 674153.171090769, 673692.100286649, 
    681277.223230072, 668071.05942577, 665564.718178651, 666711.058990101, 
    673696.183708284, 671558.897467923, 676522.610241804, 674141.217228401, 
    673543.050732869, 667038.574484619, 674693.914649553, 668050.570594258, 
    679961.019686739, 674553.355063132, 673680.378318325, 675535.019989373, 
    675110.677686158, 667729.141094734, 671370.574255653, 677504.791839875, 
    673856.50726743, 671193.888450145, 672445.432506661, 669218.725740198, 
    675515.837228226, 671942.359744591, 680270.863909815, 675158.769106064, 
    670897.110123001, 681309.014967995, 670353.402689299, 680777.476094107, 
    667190.995802724, 667296.127725616, 675961.787304345, 673866.901506047, 
    674682.875634104, 681722.532974676, 667720.125164276, 672103.489656405, 
    669525.035115157, 673654.801179336, 673339.191873988, 680988.858949506, 
    679889.386295735, 673796.589880267, 679983.731435357, 681775.226835674, 
    678497.671532893, 672717.768223632, 671790.081252952, 674253.189995415, 
    667673.022026551, 676476.403607437, 667064.10927625, 677332.165303351, 
    675167.802311261, 668164.930703785, 665746.105886702, 672033.148551728, 
    679086.912386029, 668691.659808628, 667380.716535162, 674805.046038767, 
    666796.510732712, 674740.601822875, 673559.173481894, 679422.455893958, 
    673237.222688092, 666509.819078366, 678179.756580155, 671073.2, 
    671846.630856434, 674214.635730867, 665221.637244241, 667387.875332845, 
    674361.459633023, 666570.562946823, 680170.970241638, 675854.846307953, 
    680249.938333593, 675445.296364753, 680950.380369809, 677480.315843529, 
    677412.473334924, 667886.111895438, 665484.401296523, 677827.506345478, 
    674490.30239898, 680617.792953787, 671892.884138512, 678783.57697544, 
    670058.281406317, 672563.924717641, 673025.380630848, 665826.121683051, 
    662615.291212428, 673557.685051616, 680381.771984728, 675635.39682936, 
    669508.48734755, 679595.812250766, 672820.17685585, 680044.785846734, 
    672160.00359078, 666986.966783969, 667055.492857889, 675398.548168494, 
    678444.820100166, 672920.801805885, 673226.674377164, 679975.341392769, 
    671928.10295064, 674113.130131869, 669700.029261194, 671565.260755304, 
    675449.763580816, 677525.38940721, 671803.979964415, 678296.57371787, 
    672589.350161339, 679659.72143051, 675015.80901166, 678970.555096834, 
    665874.504210837, 680834.414749603, 671886.746592884, 679739.24640989, 
    675287.257833053, 680669.694523602, 673355.448511096, 680647.618498599, 
    674658.464017147, 677378.43281873, 674075.662422715, 674934.450681024, 
    671454.105599318, 672479.39642517, 674564.735094291, 672466.005171173, 
    667608.341554342, 671409.843113201, 671275.896880385, 676450.173041056, 
    669998.236725282, 671176.785391868, 676378.72273442, 671384.001568555, 
    674270.11574684, 673204.819658812, 668829.693053063, 674058.195238848, 
    680744.286744339, 679304.653312707, 675197.984173916, 672024.148002389, 
    675905.942881457, 681087.504644224, 665129.05227684, 673563.924064378, 
    665000.76657657, 676487.011705431, 667515.826283513, 680243.204668531, 
    668726.931833338, 675324.485227373, 681597.850948541, 666996.681770089, 
    678135.163191119, 680344.727992494, 681595.374715804, 674657.172107173, 
    672531.80101063, 680825.448154394, 672577.695336555, 680980.569382554, 
    672843.259179118, 672728.495563952, 668564.638166808, 679606.252632499, 
    666756.676909919, 666958.364780974, 669521.466006942, 667982.188335304, 
    676545.698910113, 667016.411645685, 681629.318715431, 674698.419666986, 
    666623.340069735, 672260.912546061, 668314.858869761, 676737.078142768, 
    673578.100060406, 670760.200446419, 676109.1446119, 672198.985050147, 
    672904.680705589, 674700.276627365, 677480.864458848, 668312.204598566, 
    670660.011948142, 679015.49679384, 674127.084105172, 670919.150134583, 
    672190.083377811, 670173.180244691, 678234.000493896), YCOORD = c(7173725.94137568, 
    7178512.21158026, 7188004.37286458, 7184451.62263143, 7182540.89158854, 
    7177602.10731564, 7174554.67800998, 7178378.91550859, 7187781.66016957, 
    7180691.73204068, 7181551.06935712, 7184609.84807885, 7174841.43725564, 
    7182070.06473886, 7187757.94295277, 7173826.83302758, 7172966.97649723, 
    7179196.10051061, 7187219.26625456, 7178650.05549107, 7183273.24631067, 
    7188086.53135988, 7182402.21641415, 7174799.94283648, 7179047.34663232, 
    7192364.31655291, 7178698.14869023, 7180578.054145, 7183609.50509827, 
    7179755.21287062, 7181488.43542369, 7176053.41199506, 7176610.60841773, 
    7192429.63148484, 7186340.8522559, 7192401.26020501, 7185665.22539902, 
    7190259.19332797, 7178062.64680119, 7174196.39874751, 7186357.8447545, 
    7186830.78153868, 7187182.69538684, 7184273.41229388, 7183996.60498848, 
    7172471.62776314, 7176191.66737558, 7183493.17920792, 7178677.5804438, 
    7178701.5160718, 7183409.62225517, 7186442.2344699, 7181505.30321356, 
    7177295.69644443, 7173564.35508422, 7184372.92358431, 7185904.46155758, 
    7185854.76392573, 7191655.99908867, 7178419.27132338, 7187359.04310991, 
    7181562.95620387, 7189832.78665774, 7178405.08164717, 7177421.3019671, 
    7186342.44208749, 7190106.5387689, 7172100.85461554, 7180518.51308029, 
    7182162.37189482, 7181711.34182989, 7176067.76851403, 7179995.86628659, 
    7185893.86814826, 7188803.11139037, 7178641.8049244, 7181174.85514829, 
    7174718.07829741, 7182545.26039515, 7177021.15660879, 7179363.78604516, 
    7189787.39164086, 7183057.61667565, 7180370.46352127, 7182536.50644706, 
    7175856.17429819, 7185733.78926637, 7179922.69391763, 7184661.47976455, 
    7191300.65330194, 7179436.92905815, 7189475.11176155, 7176532.87387335, 
    7188996.60986567, 7177051.45185425, 7190642.66112805, 7191023.74027933, 
    7181457.85438486, 7191356.96881301, 7181600.02384124, 7191668.88320209, 
    7190405.47514902, 7171569.07377314, 7188557.51388467, 7191052.39979869, 
    7184871.26858733, 7179583.55283725, 7175137.83548175, 7184871.26858733, 
    7176126.22803763, 7191898.71638177, 7188113.82057825, 7192141.35313777, 
    7179509.19197192, 7185410.35258139, 7180265.8340292, 7176269.51941639, 
    7184522.10886742, 7180045.11365428, 7177591.35027408, 7175486.50529942, 
    7192009.49396783, 7181020.17029813, 7172651.59920887, 7186842.58521342, 
    7177759.38383706, 7190772.50659303, 7179222.03079122, 7174803.30971618, 
    7174823.13725962, 7176739.12690054, 7173841.34116444, 7185807.08527682, 
    7181874.92239315, 7177932.47748312, 7182510.85647914, 7191465.95263215, 
    7190104.3428372, 7174284.32797135, 7175372.24324758, 7176467.60835368, 
    7183137.19912919, 7175369.77070907, 7184595.21741807, 7188608.66372712, 
    7179814.14193637, 7174329.58671718, 7173973.2316374, 7180169.86506811, 
    7180136.65145395, 7174098.57539929, 7181816.31294278, 7184749.18651053, 
    7191498.32952826, 7182075.57470226, 7182514.8777278, 7176887.06871899, 
    7191394.67936099, 7186342.44208749, 7186195.14465179, 7188541.81364843, 
    7182177.45516986, 7178898.40952607, 7188761.57754439, 7193679.03359908, 
    7189134.56918379, 7187141.1424181, 7178495.96156606, 7179991.8, 
    7184607.42922245, 7188993.09134574, 7185933.97111437, 7181882.49828352, 
    7192015.92067727, 7184611.45754631, 7174375.6374188, 7178588.51012769, 
    7189758.89525777, 7178852.00693732, 7178303.94148737, 7173465.76961705, 
    7181274.56200076, 7178195.21091338, 7185440.13893693, 7184590.27302315, 
    7169648.24421533, 7187817.82600578, 7179372.86672541, 7191525.26282931, 
    7176475.82001401, 7188472.86971808, 7175607.40441939, 7186657.02125021, 
    7183522.49339943, 7178997.3146773, 7182535.67764572, 7181265.29818807, 
    7178119.3, 7182621.2516785, 7169176.67917121, 7185992.29757375, 
    7173765.88036137, 7190000.77137766, 7168897.4006902, 7180667.13784854, 
    7180638.06763668, 7185887.98468136, 7189242.4543816, 7188394.91132355, 
    7186531.29222717, 7182619.62025883, 7187284.29195676, 7173776.74294415, 
    7183086.68714786, 7184647.1333554, 7175292.09474669, 7178348.32867486, 
    7188772.30906983, 7173290.52391892, 7181546.23367645, 7171966.25655946, 
    7186350.41208792, 7175916.31464731, 7185904.46155758, 7188239.20962976, 
    7180835.29332538, 7178436.49342161, 7183276.2000648, 7187248.3830433, 
    7188922.60088947, 7177309.44269244, 7188977.14841632, 7179374.3047364, 
    7183102.83560205, 7174184.43748161, 7168745.87052316, 7173477.07317668, 
    7179211.9408117, 7186920.33133471, 7180977.42655188, 7190826.81052149, 
    7178302.84540989, 7185060.72661797, 7184361.22599172, 7184797.99756537, 
    7188493.98130519, 7184674.78582566, 7174141.57581874, 7183613.91376785, 
    7181079.90125802, 7179153.12480906, 7180286.81289454, 7174830.66167534, 
    7182738.78577826, 7182878.07776532, 7175094.0939721, 7181333.79707311, 
    7180628.33662761, 7189917.44582857, 7190070.59524101, 7180088.56497424, 
    7180439.05609377, 7192270.07059012, 7169386.7478386, 7176891.19014813, 
    7188208.8172252, 7171704.22844952, 7187063.82654005, 7186228.88248795, 
    7190143.66123866, 7180937.74686027, 7183721.77666636, 7180153.38546375, 
    7177399.4, 7181372.98798432, 7187344.70862921, 7187461.1766441, 
    7171263.79617965, 7194117.21009358, 7180364.27557273, 7184195.88999991, 
    7190885.79674296, 7178719.08551276, 7178243.58924004, 7191320.98887263, 
    7179638.81361659, 7175610.38099442, 7177293.31530251, 7180864.57717604, 
    7174684.33615746, 7174622.40866155, 7179416.99449189, 7189905.21006588, 
    7182645.31729034, 7186718.43782338, 7175722.57705951, 7189017.22988103, 
    7183209.78709416, 7186298.94090141, 7180730.89479892, 7188077.8623625, 
    7177943.75688507, 7182572.50315311, 7178180.97722471, 7181039.1682373, 
    7189057.63245085, 7181361.49057042, 7182656.31193853, 7181945.23503273, 
    7194840.40666381, 7181638.01280171, 7174818.5240795, 7183540.18026874, 
    7186312.87922608, 7179224.24918519, 7172860.14208346, 7182597.7592936, 
    7184871.26858733, 7178528.95091716, 7187681.58357669, 7191918.06791196, 
    7188118.34977798, 7181058.054129, 7192875.28098105, 7174762.40256622, 
    7183235.18819875, 7181392.0093461, 7182931.80294023, 7188285.8556811, 
    7182037.53365077, 7173435.94598873, 7184595.21741807, 7183283.29850756, 
    7189480.89543461, 7172849.99269455, 7185803.84000253, 7177088.56676921, 
    7177651.96114059, 7174260.23754042, 7179561.12733067, 7175179.15695629, 
    7183792.56573129, 7183937.88849477, 7190767.08415372, 7189704.54984351, 
    7192195.50563174, 7180439.67294554, 7174510.10149806, 7180741.20544529, 
    7176474.5000123, 7174415.98367517, 7192202.65172102, 7179660.06102551, 
    7174596.76557807, 7184916.16162226, 7182195.74265795, 7172496.25094676, 
    7174072.98280627, 7179447.85499022, 7181702.57679175, 7184405.30106772, 
    7188508.02257916, 7188492.22286596, 7175029.05769281, 7172279.9826472, 
    7189832.78665774, 7181274.07267782, 7180811.94406085, 7181287.03553171, 
    7188490.44597122, 7182273.15868682, 7184982.09623126, 7181366.52517876, 
    7173251.90968611, 7178514.97998427, 7183361.22330855, 7180134.42064486, 
    7179746.20452362, 7176708.10739588, 7184919.18209172, 7180363.08398711, 
    7191042.3518439, 7170686.74093445, 7188725.72154744, 7184585.64065761, 
    7192249.53298226, 7175592.36612635, 7181237.12070675, 7189460.47463999, 
    7185053.21084056, 7187692.03975336, 7174519.19616836, 7185010.41612455, 
    7186474.90805674, 7176058.51153403, 7178069.99955655, 7184572.73559724, 
    7175028.37780143, 7185073.94676006, 7183819.97270804, 7186596.26463138, 
    7184343.97192923, 7185956.94179565, 7190642.66112805, 7186275.86841334, 
    7181537.64570532, 7182073.12074562, 7189795.38418752, 7179815.35038299
    )), .Names = c("Y", "ESCMAE", "ESTCIVMAE", "GESTACAO", "GRAVIDEZ", 
"IDADEMAE", "PARTO", "PESO", "QTDFILMORT", "QTDFILVIVO", "RACACOR", 
"SEXO", "XCOORD", "YCOORD"), class = "data.frame", row.names = c(NA, 
-409L))
```

# Abaixo os dados da componente pós-neonatal

```{r}
pos<- structure(list(Y = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), ESCMAE = c(4L, 4L, 3L, 4L, 
5L, 4L, 5L, 5L, 3L, 4L, 4L, 5L, 3L, 4L, 5L, 4L, 3L, 4L, 5L, 5L, 
4L, 5L, 5L, 3L, 3L, 9L, 5L, 5L, 3L, 5L, 5L, 4L, 4L, 4L, 5L, 5L, 
4L, 4L, 5L, 4L, 5L, 3L, 3L, 3L, 5L, 4L, 5L, 4L, 5L, 5L, 4L, 4L, 
3L, 4L, 5L, 4L, 5L, 5L, 4L, 4L, 5L, 5L, 5L, 5L, 4L, 4L, 4L, 4L, 
2L, 3L, 5L, 3L, 5L, 3L, 3L, 4L, 4L, 4L, 5L, 5L, 3L, 3L, 3L, 5L, 
3L, 3L, 4L, 3L, 2L, 3L, 5L, 4L, 5L, 3L, 4L, 5L, 3L, 2L, 5L, 3L, 
3L, 5L, 2L, 5L, 4L, 3L, 5L, 3L, 3L, 4L, 3L, 3L, 3L, 4L, 3L, 4L, 
3L, 3L, 4L, 5L, 2L, 3L, 4L, 3L, 3L, 3L, 4L, 3L, 4L, 4L, 3L, 4L, 
3L, 4L, 3L, 5L, 4L, 4L, 3L, 3L, 4L, 4L, 3L, 3L, 5L, 3L, 4L), 
    ESTCIVMAE = c(2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 1L, 1L, 2L, 
    2L, 2L, 1L, 4L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 2L, 
    1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 
    2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 1L, 
    1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 3L, 1L, 1L, 
    2L, 1L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 
    2L, 1L, 2L, 2L, 2L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 1L, 1L, 2L, 
    2L, 2L, 1L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 
    1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 1L, 
    2L, 2L, 1L, 4L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 1L, 1L, 2L, 2L, 
    1L), GESTACAO = c(2L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 4L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 4L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 4L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 4L, 4L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
    5L, 5L, 5L, 6L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 4L, 
    5L, 5L, 4L, 2L, 5L, 5L, 3L, 5L, 5L, 5L, 5L, 5L, 5L, 4L, 2L, 
    5L, 5L, 3L, 5L, 5L, 3L, 5L, 4L, 5L, 4L, 5L, 5L, 5L, 5L, 5L, 
    4L, 5L, 5L, 4L, 5L, 5L, 5L, 5L, 4L, 5L, 5L, 5L, 5L, 2L, 2L, 
    4L, 5L), GRAVIDEZ = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L), IDADEMAE = c(21L, 27L, 29L, 32L, 39L, 37L, 21L, 
    30L, 22L, 20L, 23L, 24L, 27L, 17L, 38L, 22L, 17L, 19L, 27L, 
    23L, 21L, 29L, 22L, 26L, 39L, 31L, 31L, 30L, 21L, 29L, 28L, 
    25L, 30L, 26L, 27L, 32L, 18L, 36L, 24L, 29L, 35L, 28L, 26L, 
    27L, 35L, 32L, 22L, 24L, 40L, 24L, 27L, 34L, 30L, 20L, 31L, 
    26L, 18L, 27L, 16L, 29L, 25L, 35L, 27L, 31L, 17L, 22L, 18L, 
    24L, 29L, 14L, 27L, 30L, 21L, 22L, 25L, 23L, 41L, 18L, 30L, 
    24L, 22L, 29L, 31L, 21L, 26L, 16L, 28L, 28L, 19L, 23L, 28L, 
    18L, 33L, 17L, 21L, 29L, 28L, 20L, 21L, 21L, 26L, 31L, 42L, 
    23L, 20L, 30L, 35L, 19L, 30L, 26L, 37L, 20L, 20L, 16L, 18L, 
    19L, 22L, 20L, 23L, 19L, 35L, 24L, 32L, 14L, 30L, 37L, 23L, 
    15L, 20L, 18L, 28L, 37L, 19L, 18L, 34L, 21L, 44L, 18L, 23L, 
    20L, 39L, 21L, 15L, 23L, 31L, 28L, 19L), PARTO = c(1L, 2L, 
    1L, 1L, 2L, 1L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 1L, 2L, 
    2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 
    1L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 
    2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 2L, 
    2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 1L, 
    2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 
    2L, 2L, 1L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 
    2L, 1L, 1L, 1L, 2L, 1L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 1L, 2L, 
    2L, 2L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 
    1L, 1L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 1L), PESO = c(970L, 3110L, 
    3580L, 2890L, 3260L, 2840L, 2210L, 3515L, 1865L, 2885L, 2720L, 
    3220L, 3390L, 2695L, 3185L, 2900L, 2175L, 2795L, 4300L, 3195L, 
    3105L, 3100L, 3130L, 3230L, 3110L, 3070L, 2700L, 3830L, 3245L, 
    3230L, 3100L, 3355L, 2335L, 3200L, 2895L, 2885L, 3030L, 3250L, 
    3370L, 2910L, 3880L, 2945L, 3235L, 2040L, 3435L, 3840L, 3420L, 
    3410L, 3380L, 2455L, 2780L, 3500L, 2365L, 2965L, 2565L, 3240L, 
    3130L, 3450L, 3630L, 3775L, 3815L, 4050L, 3060L, 3220L, 3110L, 
    3600L, 3150L, 3145L, 3125L, 2700L, 2990L, 2700L, 2630L, 3730L, 
    4170L, 3190L, 3390L, 3020L, 3240L, 3850L, 2875L, 2950L, 3270L, 
    2700L, 4210L, 3250L, 3280L, 4355L, 2710L, 2825L, 3830L, 3105L, 
    2800L, 3330L, 3440L, 3570L, 3185L, 3090L, 3165L, 1685L, 2690L, 
    3395L, 2135L, 920L, 2780L, 3900L, 1060L, 2650L, 3260L, 2590L, 
    3315L, 4455L, 3240L, 1790L, 1170L, 2725L, 2620L, 690L, 4025L, 
    3000L, 1180L, 4050L, 3190L, 2840L, 2495L, 2490L, 3175L, 2330L, 
    3140L, 2060L, 2110L, 2800L, 3495L, 2950L, 2530L, 2970L, 1970L, 
    2810L, 2160L, 2530L, 2975L, 2670L, 2775L, 1025L, 1000L, 1545L, 
    3230L), QTDFILMORT = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 1L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 3L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 
    0L, 0L, 1L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 
    0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 1L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    1L, 0L, 0L), QTDFILVIVO = c(0L, 1L, 3L, 1L, 0L, 2L, 0L, 0L, 
    0L, 0L, 0L, 0L, 2L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 
    3L, 3L, 1L, 1L, 1L, 1L, 0L, 0L, 0L, 1L, 1L, 1L, 0L, 0L, 1L, 
    1L, 0L, 1L, 2L, 2L, 1L, 1L, 2L, 1L, 1L, 1L, 0L, 0L, 1L, 3L, 
    0L, 0L, 1L, 0L, 1L, 0L, 1L, 1L, 1L, 0L, 0L, 0L, 1L, 0L, 1L, 
    3L, 0L, 0L, 2L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 1L, 0L, 5L, 1L, 
    0L, 2L, 0L, 2L, 3L, 1L, 3L, 0L, 1L, 0L, 0L, 1L, 0L, 2L, 1L, 
    0L, 0L, 3L, 0L, 1L, 0L, 1L, 4L, 2L, 0L, 4L, 2L, 6L, 2L, 0L, 
    0L, 0L, 0L, 0L, 0L, 3L, 0L, 2L, 2L, 3L, 0L, 4L, 4L, 1L, 0L, 
    0L, 0L, 3L, 1L, 1L, 1L, 1L, 0L, 4L, 0L, 2L, 0L, 3L, 0L, 1L, 
    0L, 0L, 1L, 0L), RACACOR = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 4L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L), SEXO = structure(c(2L, 1L, 2L, 1L, 2L, 
    2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 
    1L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 
    1L, 2L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 
    1L, 2L, 2L, 1L, 1L, 2L, 1L, 1L, 1L, 2L, 2L, 1L, 1L, 1L, 2L, 
    1L, 1L, 1L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 
    2L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 2L, 1L, 
    2L, 1L, 1L, 2L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 
    2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 2L, 1L, 2L, 2L, 
    1L, 2L, 1L, 1L, 2L, 2L, 1L, 2L, 1L, 1L, 1L, 1L, 2L, 1L, 2L, 
    2L, 2L, 1L, 2L, 2L, 2L, 2L), .Label = c("F", "M"), class = "factor"), 
    XCOORD = c(668448.946240262, 671985.736275751, 676859.674899764, 
    665645.493859063, 668040.165825775, 670520.297278726, 669315.699913762, 
    675995.526932891, 680020.582183375, 672732.203961556, 680993.469030689, 
    674899.234410994, 673846.486720241, 673772.062570218, 675535.295690286, 
    671461.298696948, 675285.918754326, 680322.355449152, 671979.620071533, 
    676427.303682826, 670301.435031258, 667090.230319784, 675873.274035388, 
    673000.533297415, 667739.038972215, 670468.487100868, 674791.349336724, 
    676845.309731572, 667628.603601831, 675845.727974953, 676506.846661556, 
    675689.271662818, 673597.209319812, 667491.408242315, 674232.188452118, 
    675730.610411633, 676566.947368839, 672606.527655585, 674594.63531286, 
    673075.877233663, 671937.096423512, 676350.409183057, 666774.292038885, 
    675961.787304345, 677434.003822773, 674044.488622262, 676534.944393934, 
    675267.965214657, 671184.437483064, 671003.660713133, 667614.765539057, 
    677584.532498933, 674793.988379047, 677918.714668349, 674742.187421294, 
    671311.59283779, 680500.825439937, 669578.918982908, 675597.760716392, 
    679891.798444003, 668674.032334575, 677264.895306089, 680984.275815994, 
    676710.608331455, 669179.794038987, 679522.047010229, 678052.964178095, 
    680038.03744353, 672383.590880282, 664930.716062329, 674541.602733188, 
    668155.757156845, 667264.91352088, 674797.173835228, 674381.898150153, 
    681195.884450463, 681482.418807558, 677060.917152398, 669080.260964266, 
    675796.765862376, 673681.609517084, 679805.097813724, 674635.621203297, 
    680306.7645085, 681215.192051749, 676476.403607437, 667840.694310495, 
    676772.915678561, 674147.453755662, 672836.024637179, 672135.624166208, 
    671469.767538761, 676253.981384524, 680685.938125543, 671317.15730011, 
    679086.912386029, 678379.06299241, 666615.405450947, 680557.46341977, 
    673613.319247246, 681098.991408757, 681355.211267877, 666230.390303907, 
    675102.890739582, 671257.59664081, 678303.680145049, 664937.586919384, 
    678798.142288247, 674854.341085567, 671158.426030859, 663546.86129595, 
    673795.518346468, 676708.956295487, 666041.008945489, 675327.798733551, 
    675907.942872251, 671914.071455394, 675003.100601857, 672569.795694651, 
    679533.002267448, 673048.199430233, 666729.823940964, 681480.958348516, 
    675687.18348326, 674211.126020637, 668587.961954276, 666427.694127905, 
    681344.017321851, 672902.671125637, 679217.484943053, 668923.515756628, 
    673184.513371753, 668781.667239516, 680215.970892737, 666478.944932232, 
    668346.44187009, 672924.273280495, 674271.255672665, 676532.580697043, 
    675003.730388506, 676449.000985217, 674892.073431232, 666377.119831376, 
    671678.409530754, 666036.248578624, 677598.319862339, 667495.860598914
    ), YCOORD = c(7177479.47929991, 7184444.75124225, 7174607.53425045, 
    7187138.90958041, 7183237.32794969, 7183137.19912919, 7179120.62969522, 
    7192329.08921693, 7182393.12748895, 7176561.91382775, 7186593.18286663, 
    7186222.39439666, 7193332.82472306, 7178012.16782719, 7187170.06498934, 
    7179653.04914047, 7172645.45446732, 7188223.55770265, 7177759.38383706, 
    7181438.5692315, 7182566.73880334, 7174284.36995885, 7173322.08454714, 
    7173873.77799459, 7181170.72680661, 7185955.89405295, 7178565.34471633, 
    7176269.51941639, 7191813.01203404, 7188357.59700981, 7177886.02642871, 
    7185036.64287307, 7187707.55745605, 7180032.09055334, 7175232.61402425, 
    7179857.5038701, 7192331.66650634, 7173886.02713743, 7186629.78921736, 
    7191977.65881945, 7183550.90041954, 7189631.87009564, 7181431.7964974, 
    7173477.07317668, 7185289.41516201, 7193126.08001804, 7176406.8474867, 
    7187275.53246189, 7186098.21662974, 7185897.77733605, 7181457.85438486, 
    7181265.29818807, 7173574.53580495, 7178615.61603738, 7189967.32046033, 
    7179554.69867184, 7184254.98278565, 7181600.02384124, 7173765.74382852, 
    7191220.28071221, 7182535.67764572, 7191023.74027933, 7186935.10937894, 
    7176581.33902591, 7192480.8528192, 7183464.61464561, 7180316.58770069, 
    7183449.1494608, 7182984.2539508, 7188442.81857304, 7179222.03079122, 
    7177735.05593193, 7169176.67917121, 7185981.26965581, 7185654.30067694, 
    7187368.49469498, 7180193.37594766, 7191287.43115541, 7183840.76696003, 
    7178136.8109435, 7181051.56591152, 7181173.6760498, 7176160.15529717, 
    7187003.68651053, 7191256.21823405, 7175094.0939721, 7191532.78323598, 
    7173973.2316374, 7177844.91193193, 7173831.45323731, 7182217.05730843, 
    7174081.94543828, 7185419.5435652, 7186554.13285489, 7174128.58972474, 
    7192270.07059012, 7178691.94953461, 7182605.41541472, 7182176.96343932, 
    7174800.32203863, 7188539.46401896, 7190618.24382067, 7185782.40334385, 
    7179102.82199077, 7180697.72198056, 7184473.06541571, 7181045.31487659, 
    7183947.72958593, 7184150.18339197, 7175897.04659666, 7183497.262586, 
    7179383.66946526, 7175269.85243441, 7183334.69824696, 7193021.85768562, 
    7174057.02463406, 7173901.68446385, 7179341.14615158, 7174804.82456942, 
    7189063.5071761, 7175558.16903171, 7179847.44010058, 7188874.53062563, 
    7186752.0173367, 7177807.72120884, 7170322.88964504, 7183690.72886089, 
    7182964.98895816, 7181319.365405, 7182679.65617837, 7178690.72244026, 
    7184536.14116229, 7183458.97546013, 7182502.61379027, 7181127.20208713, 
    7184693.59259778, 7186551.66364833, 7194400.32708733, 7174870.0509796, 
    7192162.26915368, 7174196.22235416, 7174920.83566339, 7180111.83623594, 
    7184137.10222797, 7179782.15628375, 7176163.18767714, 7171990.67869711
    )), .Names = c("Y", "ESCMAE", "ESTCIVMAE", "GESTACAO", "GRAVIDEZ", 
"IDADEMAE", "PARTO", "PESO", "QTDFILMORT", "QTDFILVIVO", "RACACOR", 
"SEXO", "XCOORD", "YCOORD"), class = "data.frame", row.names = c(NA, 
-147L))
```

